### ISSUE TITLE
The wrong request is made for the logo game

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#149]
The wrong request is made for the logo game following the refactoring.

@raphael0202 reports that Robotoff expects directly `annotations` and not nested within `params`

![image](https://user-images.githubusercontent.com/1689815/102110644-b5402200-3e35-11eb-9d35-9b3cd5c76933.png)

https://github.com/openfoodfacts/openfoodfacts-hungergames/commit/8b01bd4e94c073e5558b01127c0a7253a8d75de8#diff-6686fad6d857f4ead84af89b910e8c0538216413547bac07a7afa163615211b4

**Comment by astagi** [comment]
Fixed https://github.com/openfoodfacts/openfoodfacts-hungergames/commit/e4dccf894d52527b7a1953820e2548b22e58e629

Please check it and close the issue if it's ok!

**Comment by teolemon** [comment]
I think it's fixed. I'm seeing a similar issue for Insight search: https://hunger.openfoodfacts.org/insights
Access to XMLHttpRequest at 'https://robotoff.openfoodfacts.org/api/v1/insights?page=1&count=25' from origin 'https://hunger.openfoodfacts.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by teolemon** [comment]
https://deploy-preview-151--gifted-lalande-686eef.netlify.app/logos @astagi

**Comment by teolemon** [comment]
You get automatic previews if you go through a branch instead of directly committing to master

**Comment by astagi** [comment]
Sure @teolemon I implemented CD on Netlify for Hunger Games :) I pushed to master cause it was a silly and easy to fix error I made during refactoring... Anyway opening a PR is always the best thing to do! Let me see what happens for Insight search and let you know

**Comment by astagi** [comment]
@teolemon this is the commit with Insights refactoring https://github.com/openfoodfacts/openfoodfacts-hungergames/commit/e3a54770f5a1063a911505c2443fc2ca38ea3df4

**Comment by teolemon** [comment]
ok, https://github.com/openfoodfacts/robotoff/issues/313
