### ISSUE TITLE
Access to XMLHttpRequest at 'https://robotoff.openfoodfacts.org/api/v1/insights/annotate' from origin 'https://hunger.openfoodfacts.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#192]
Access to XMLHttpRequest at 'https://robotoff.openfoodfacts.org/api/v1/insights/annotate' from origin 'https://hunger.openfoodfacts.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by teolemon** [comment]
While playing on https://hunger.openfoodfacts.org/questions?type=brand&country=en%3Aitaly
Also: 
Uncaught (in promise) Error: Network Error
    at t.exports (createError.js:16)
    at XMLHttpRequest.h.onerror (xhr.js:84)

**Comment by teolemon** [comment]
prob related to robotoff.openfoodfacts.org/api/v1/insights/annotate:1 Failed to load resource: net::ERR_FAILED

**Comment by alexfauquette** [comment]
Impossible to reproduce.
We solved CORS error multiple times from march, so I propose to close this issue
