### ISSUE TITLE
The Weight game goes back to labels and categories after a few questions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#203]
The Weight game goes back to labels and categories after a few questions.
As a result, it's not possible to validate more than a few insights.
https://hunger.openfoodfacts.org/questions?type=product_weight

**Comment by alexfauquette** [comment]
I can not reproduce the bug. 

After annotating 171 products and skipping much more The app is still displaying weight question.

Probably solved

**Comment by teolemon** [comment]
Let's close it
