### ISSUE TITLE
Misleading string

### ISSUE THREAD

**Issue by yarons** [openfoodfacts/openfoodfacts-hungergames#229]
This string appear for translation yet it is some sort of code, any way to fix?

https://github.com/openfoodfacts/openfoodfacts-hungergames/blob/b616ef8bbdabc91036514f42f00fbedc46e16fdc/src/i18n/common.json#L32

https://crowdin.com/translate/openfoodfacts/1942/en-he#173424

Thanks!

**Comment by alexfauquette** [comment]
It seems to be an advanced usage of i18n (I never saw that before)

`@:settings.settings` means "use the translation located at `settings.settings`"

Such that in the menu, we can use `menu.settings` and the text will be same as `settings.settings`

**Comment by alexfauquette** [comment]
Would you like to remove this symbolic link to avoid misleading translation keys?

**Comment by yarons** [comment]
This is great but it should be removed from Crowdin or the translation file, the translator shouldn't see or be able to translate it.

**Comment by alexfauquette** [comment]
@teolemon Do you know how to do? 

I only see two solutions : 
 - [easy] dev does not use these `@:` trick
 - [uncertain] find a way to remove from crowding translations starting with `@:`

**Comment by teolemon** [comment]
The first one is the right one, obviously

**Comment by yarons** [comment]
It's only one string so removing from Crowdin should be fairly easy (even if there were many it's possible to just search for all of them and disable them).
