### ISSUE TITLE
Issue on the logo page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#24]
![image](https://user-images.githubusercontent.com/1689815/84768036-cbc70700-afd3-11ea-823d-9fe4ae2e2c79.png)
We can't annotate anymore. Not sure if Robotoff or Hunger Games related, but this came up in the console.

**Comment by raphael0202** [comment]
It was due to a temporary outage of robotoff, it works now. I'm closing the issue.
