### ISSUE TITLE
The deep link to a specific brand is broken

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#247]
Story: The deep link to a specific brand is broken
https://hunger.openfoodfacts.org/?type=brand#/questions?type=brand&value_tag=coca-cola
![image](https://user-images.githubusercontent.com/1689815/132089914-2cba91b7-9635-42f6-a1af-08c4b6eeedda.png)

**Comment by teolemon** [comment]
- As a FYI, we also broke the link on the production Android app: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4220

**Comment by CharlesNepote** [comment]
It's very annoying for big users. I used to validate thousands of products per session thanks to this link, it's now more complicated...
I would say it's a P1 issue.

**Comment by alexfauquette** [comment]
Should not be a problem any more. Urls are back to the normal
