### ISSUE TITLE
Add packaging in labelling options

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#25]
![image](https://user-images.githubusercontent.com/1689815/85197603-6c723b00-b2e2-11ea-9ed5-f26fb974e080.png)

**Comment by teolemon** [comment]
https://hunger.openfoodfacts.org/logos?logo_id=501152
https://hunger.openfoodfacts.org/logos?logo_id=217266
https://hunger.openfoodfacts.org/logos?logo_id=173640
https://hunger.openfoodfacts.org/logos?logo_id=466824

**Comment by raphael0202** [comment]
Add packaging as type you mean?

**Comment by teolemon** [comment]
I would also let the user store a value

**Comment by raphael0202** [comment]
I've added it as a type, it's also possible to store a value.
