### ISSUE TITLE
Add the UI to allow to filter by brand

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#278]
### What

- [ ] While documenting Robotoff, I realized that brand filtering was possible https://robotoff.openfoodfacts.org/api/v1/questions/random?lang=fr&insight_types=category&server_domain=api.openfoodfacts.org&count=10&value_tag=en:bcaa&country=en:france&brands=ironmaxx
- [ ] This means we could create brand specific views, useful to get producer to validate data about their products, or to ensure a brand is well completed after an import

**Comment by alexfauquette** [comment]
Already possible to do it with URL search param

https://hunger.openfoodfacts.org/questions?brand=ironmaxx&type=category

**Comment by teolemon** [comment]
Thanks 👍 
I've clarified, and I've created a few related bugs (that could be useful for producers)

**Comment by alexfauquette** [comment]
PR #295
