### ISSUE TITLE
2 strings are missing from the translation file

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#306]
### What

- [ ] 2 strings are missing from the translation file

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/135706954-006dec0e-abe1-4048-933b-d01c0157ec0a.png)

**Comment by alexfauquette** [comment]
Hi @tspencer244, I just saw your commit. The issue was misleading. Strings were not missing, the translation key was wrong. 

If you want, you can @ me on issues to get more technical details on them

**Comment by tspencer244** [comment]
No problemo, I got stuck trying to get Crowdin to work and gave up on this task anyway :slightly_smiling_face:
