### ISSUE TITLE
Add a new type for categories

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#31]
![image](https://user-images.githubusercontent.com/1689815/85622503-37117880-b667-11ea-8d0d-6bb2d17c97df.png)
https://hunger.openfoodfacts.org/logos?logo_id=565064

**Comment by teolemon** [comment]
Also happens for thinks like Grana Padano

**Comment by teolemon** [comment]
Mozarella di Buffala Campana: https://hunger.openfoodfacts.org/logos?logo_id=77349

**Comment by raphael0202** [comment]
Done (637c10d14ae5964fd291542dd247dc1aa021cf10).
