### ISSUE TITLE
Allow to filter answers by country

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#37]
Allow to filter answers by country in the interface, in addition to the already hidden parameter

https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Aorganic&country=en%3Afrance
We have a list of countries at: https://static.openfoodfacts.org/data/taxonomies/countries.json

**Comment by jolesh** [comment]
So basically we just have to add a drop down menu where you can select a country and it then sends you to the link with the hidden parameter?

**Comment by teolemon** [comment]
Yes

**Comment by teolemon** [comment]
@alexfauquette I believe it's closed. I'm opening another one to make the filter visible in the UI
