### ISSUE TITLE
Proposal to add contributing guidelines

### ISSUE THREAD

**Issue by sumana2001** [openfoodfacts/openfoodfacts-hungergames#401]
Contributing guidelines would provide potential project contributors with a short guide to how they can contribute to the particular application. It would help contributors understand how to open a PR or raise issues. Adding Contributing guidelines would help maintainers and contributors work in symphony and with ease. Ultimately, increase the productivity of both the stakeholders.

While contributing I realized, the contributing guidelines are not present so I directly sent a pr to the master branch. As you asked me to create a branch and then send a PR, we can also mention that in the contribution guidelines to make it easier for both contributor and the maintainer.
@alexfauquette sir, if this is something you feel is good to add to the repository, feel free to assign it to me.

**Comment by alexfauquette** [comment]
Yes, any improvement in the documentation for future contributors is welcome.

I added you to the project, you should be able to assign yourself

**Comment by sumana2001** [comment]
Thank you! Will create a branch and send the PR
