### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by sumana2001** [openfoodfacts/openfoodfacts-hungergames#451]
A 404 page is a landing page that tells your site viewers the requested page is unavailable or, in some cases, doesn't exist. At present, if a user reaches a page that does not exist, the hunger games website shows the blank page with the navbar. Instead, we can add an attractive view in such cases that tell the user where to go from there. 

Currently how it looks:
![image](https://user-images.githubusercontent.com/63084088/169031841-f4314ed4-8685-4657-a151-e347fdb95062.png)

How I think it should look:
![image](https://user-images.githubusercontent.com/63084088/169031764-820f8ba1-2bb7-4c79-b9e6-a156fe64f513.png)

@alexfauquette  if this is something you feel is good to add to the website, feel free to assign it to me.

**Comment by alexfauquette** [comment]
For small improvements such as this one, feel free to open a PR directly
