### ISSUE TITLE
Lazyload images for a faster logo game experience

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#49]
As suggested by Philippe, Lazyload images for a faster logo game experience.
He proposes the following lib:
https://github.com/verlok/vanilla-lazyload

**Comment by hangy** [comment]
We used to use such a library with openfoodfacts-server in the past but have switched to [`loading="lazy"`](https://caniuse.com/#feat=loading-lazy-attr) [a while ago](https://github.com/openfoodfacts/openfoodfacts-server/pull/1962). No complaints so far, and still faster loading for modern browsers.
