### ISSUE TITLE
Make Hunger Games multilingual

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#55]
Make Hunger Games multilingual by adding:
- [x]  translation support for the User Interface
- [x]  localized Robotoff question loading.

**Comment by alexfauquette** [comment]
I saw there is a platform for translating OFF, should we integrate hunger games to this translation platform, or we just use an hand made json file per language ?

**Comment by raphael0202** [comment]
It would be better to integrate it to the translation platform in my opinion, as it is used across all the OFF projects.

**Comment by astagi** [comment]
I've opened a PR to add i18n https://github.com/openfoodfacts/openfoodfacts-hungergames/pull/56

**Comment by teolemon** [comment]
Great 👍

**Comment by teolemon** [comment]
For Crowdin integration, you need to place a crowdin.yml file at the root of the repository
```
files:
  - source: /i18n/MY_SUPER_FILE.json
    translation: /i18n/%two_letters_code%/MY_SUPER_FILE.json
```

**Comment by astagi** [comment]
Thanks @teolemon I didn't know Crowdin, I'll add the required files to integrate it!

**Comment by astagi** [comment]
@teolemon PR updated with Crowdin integration. I made a file `common.json` containing all the labels translated to english, do you think is ok keeping `common.json` and `en.json`? At the moment they have the same content, I see that inside the [openfoodfacts.pot](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/po/openfoodfacts/openfoodfacts.pot) file the translation is empty.

**Comment by alexfauquette** [comment]
Is that just about adding the field `lang` in robotoff request for insights or am I missing something?

**Comment by teolemon** [comment]
it should be it

**Comment by teolemon** [comment]
@alexfauquette I believe this is fixed

**Comment by alexfauquette** [comment]
Yes, there is some game that maybe need some cleaning, but the integration with crowding is here
