### ISSUE TITLE
Logos too large in portrait mode

### ISSUE THREAD

**Issue by hangy** [openfoodfacts/openfoodfacts-hungergames#68]
Since #64 was deployed, the portrait mode of the logos game is less usable than before on mobile. I used to see ≥2 rows with ≥4 images on this page, which made labelling logos quite efficient.
Now, I can just see ≤2 logos at all - in total, which makes this view unusable to me: ![Screenshot_20200721-010029_Chrome](https://user-images.githubusercontent.com/87124/87994754-0994df00-caee-11ea-91c5-3aa4c0fe8f93.png)

Landscape mode is better, but also doesn't come close to the previous portrait layout, IMHO: ![Screenshot_20200721-010049_Chrome](https://user-images.githubusercontent.com/87124/87994958-8627bd80-caee-11ea-9a9c-24e94bc1af09.png)

**Comment by raphael0202** [comment]
Fixed in ee18ab5.

**Comment by astagi** [comment]
@hangy @raphael0202 my bad sorry 😞 I didn't test it on mobile landscape!

I opened another PR to display logos correctly on mobile portrait and landscape https://github.com/openfoodfacts/openfoodfacts-hungergames/pull/70

let me know what you think

**Comment by raphael0202** [comment]
@astagi I already fixed this issue in ee18ab5a68c767514de05bd29bf428fdf4ae1e5e, do you still experience the problem?

**Comment by astagi** [comment]
Sorry @raphael0202 I've just updated #70 PR 👍 I've seen your fix but using 3 columns, users may experience #58 issue in portrait mode on mobile devices. With this PR you'll have 2 columns in portrait mode and 4 columns in landscape mode (screenshots attached).
