### ISSUE TITLE
[Feat] Allow forcing language using the URL

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames#74]
### What
We'd need to be able to force the language by URL to integrate within the app: 
`https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Avinegars&country=en%3Aunited-states&language=fr`

**Comment by alexfauquette** [comment]
already implemented (need to deploy master)

https://deploy-preview-226--gifted-lalande-686eef.netlify.app/questions?language=fr
https://deploy-preview-226--gifted-lalande-686eef.netlify.app/questions?language=de
https://deploy-preview-226--gifted-lalande-686eef.netlify.app/questions?language=en
