### ISSUE TITLE
Hunger games: skip product if no image available

### ISSUE THREAD

**Issue by SantosSi** [openfoodfacts/openfoodfacts-hungergames#87]
**Describe the bug**
The user is presented a product, but instead of showing an image to enable the user to find visual evidence, the message "No image available" is displayed.

**To Reproduce**
1. Go to 'https://de.openfoodfacts.org/hunger-game'
2. Answer questions until the message "https://de.openfoodfacts.org/hunger-game" instead of an image

**Expected behavior**
Do not present questions when no image available.

**Timeloss per product**
1-2 seconds

**Comment by SantosSi** [comment]
Still happening on https://de.openfoodfacts.org:
> Kakao Pur Dattel Haselnuss mit Kakaonibs
> No image available
> Gehört das Produkt zu dieser Kategorie?
> Frühstückscerealien
and without a product name:
> No image available
> Gehört das Produkt zu dieser Kategorie?
> Native Olivenöle Extra

**Comment by VaiTon** [comment]
I don't know about the state of deployment. @teolemon ?
